name: python-helloworld
tag: latest
on: 
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    -
      name: Checkout
      uses: actions.checkout@v2
    -
      name: Setup QEMU
      used: docker/setup-qemu-action@v1
    -
      name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platform: linux/amd64
        push: true
        tags: vjsolver/python-helloworld:latest

